/**
 * Códigos de marcación E.164 (ITU) con nombres en español.
 * El código va SIN '+'. Varios países comparten código (NANP = '1'):
 * para parsear, PARSE_PRIORITY decide el empate.
 */
export interface Country {
  iso: string;
  name: string;
  code: string;
}

/** Países frecuentes del producto: aparecen primero en el selector. */
export const FREQUENT_ISOS = [
  'PE',
  'MX',
  'CO',
  'AR',
  'CL',
  'EC',
  'BO',
  'VE',
  'BR',
  'US',
  'ES',
] as const;

/** Lista completa, ordenada alfabéticamente por nombre en español. */
export const COUNTRIES: Country[] = [
  { iso: 'AF', name: 'Afganistán', code: '93' },
  { iso: 'AL', name: 'Albania', code: '355' },
  { iso: 'DE', name: 'Alemania', code: '49' },
  { iso: 'AD', name: 'Andorra', code: '376' },
  { iso: 'AO', name: 'Angola', code: '244' },
  { iso: 'AI', name: 'Anguila', code: '1' },
  { iso: 'AG', name: 'Antigua y Barbuda', code: '1' },
  { iso: 'SA', name: 'Arabia Saudita', code: '966' },
  { iso: 'DZ', name: 'Argelia', code: '213' },
  { iso: 'AR', name: 'Argentina', code: '54' },
  { iso: 'AM', name: 'Armenia', code: '374' },
  { iso: 'AW', name: 'Aruba', code: '297' },
  { iso: 'AU', name: 'Australia', code: '61' },
  { iso: 'AT', name: 'Austria', code: '43' },
  { iso: 'AZ', name: 'Azerbaiyán', code: '994' },
  { iso: 'BS', name: 'Bahamas', code: '1' },
  { iso: 'BD', name: 'Bangladés', code: '880' },
  { iso: 'BB', name: 'Barbados', code: '1' },
  { iso: 'BH', name: 'Baréin', code: '973' },
  { iso: 'BE', name: 'Bélgica', code: '32' },
  { iso: 'BZ', name: 'Belice', code: '501' },
  { iso: 'BJ', name: 'Benín', code: '229' },
  { iso: 'BM', name: 'Bermudas', code: '1' },
  { iso: 'BY', name: 'Bielorrusia', code: '375' },
  { iso: 'BO', name: 'Bolivia', code: '591' },
  { iso: 'BQ', name: 'Bonaire', code: '599' },
  { iso: 'BA', name: 'Bosnia y Herzegovina', code: '387' },
  { iso: 'BW', name: 'Botsuana', code: '267' },
  { iso: 'BR', name: 'Brasil', code: '55' },
  { iso: 'BN', name: 'Brunéi', code: '673' },
  { iso: 'BG', name: 'Bulgaria', code: '359' },
  { iso: 'BF', name: 'Burkina Faso', code: '226' },
  { iso: 'BI', name: 'Burundi', code: '257' },
  { iso: 'BT', name: 'Bután', code: '975' },
  { iso: 'CV', name: 'Cabo Verde', code: '238' },
  { iso: 'KH', name: 'Camboya', code: '855' },
  { iso: 'CM', name: 'Camerún', code: '237' },
  { iso: 'CA', name: 'Canadá', code: '1' },
  { iso: 'QA', name: 'Catar', code: '974' },
  { iso: 'TD', name: 'Chad', code: '235' },
  { iso: 'CL', name: 'Chile', code: '56' },
  { iso: 'CN', name: 'China', code: '86' },
  { iso: 'CY', name: 'Chipre', code: '357' },
  { iso: 'VA', name: 'Ciudad del Vaticano', code: '379' },
  { iso: 'CO', name: 'Colombia', code: '57' },
  { iso: 'KM', name: 'Comoras', code: '269' },
  { iso: 'KP', name: 'Corea del Norte', code: '850' },
  { iso: 'KR', name: 'Corea del Sur', code: '82' },
  { iso: 'CI', name: 'Costa de Marfil', code: '225' },
  { iso: 'CR', name: 'Costa Rica', code: '506' },
  { iso: 'HR', name: 'Croacia', code: '385' },
  { iso: 'CU', name: 'Cuba', code: '53' },
  { iso: 'CW', name: 'Curazao', code: '599' },
  { iso: 'DK', name: 'Dinamarca', code: '45' },
  { iso: 'DM', name: 'Dominica', code: '1' },
  { iso: 'EC', name: 'Ecuador', code: '593' },
  { iso: 'EG', name: 'Egipto', code: '20' },
  { iso: 'SV', name: 'El Salvador', code: '503' },
  { iso: 'AE', name: 'Emiratos Árabes Unidos', code: '971' },
  { iso: 'ER', name: 'Eritrea', code: '291' },
  { iso: 'SK', name: 'Eslovaquia', code: '421' },
  { iso: 'SI', name: 'Eslovenia', code: '386' },
  { iso: 'ES', name: 'España', code: '34' },
  { iso: 'US', name: 'Estados Unidos', code: '1' },
  { iso: 'EE', name: 'Estonia', code: '372' },
  { iso: 'SZ', name: 'Esuatini', code: '268' },
  { iso: 'ET', name: 'Etiopía', code: '251' },
  { iso: 'PH', name: 'Filipinas', code: '63' },
  { iso: 'FI', name: 'Finlandia', code: '358' },
  { iso: 'FJ', name: 'Fiyi', code: '679' },
  { iso: 'FR', name: 'Francia', code: '33' },
  { iso: 'GA', name: 'Gabón', code: '241' },
  { iso: 'GM', name: 'Gambia', code: '220' },
  { iso: 'GE', name: 'Georgia', code: '995' },
  { iso: 'GH', name: 'Ghana', code: '233' },
  { iso: 'GI', name: 'Gibraltar', code: '350' },
  { iso: 'GD', name: 'Granada', code: '1' },
  { iso: 'GR', name: 'Grecia', code: '30' },
  { iso: 'GL', name: 'Groenlandia', code: '299' },
  { iso: 'GP', name: 'Guadalupe', code: '590' },
  { iso: 'GU', name: 'Guam', code: '1' },
  { iso: 'GT', name: 'Guatemala', code: '502' },
  { iso: 'GF', name: 'Guayana Francesa', code: '594' },
  { iso: 'GG', name: 'Guernsey', code: '44' },
  { iso: 'GN', name: 'Guinea', code: '224' },
  { iso: 'GQ', name: 'Guinea Ecuatorial', code: '240' },
  { iso: 'GW', name: 'Guinea-Bisáu', code: '245' },
  { iso: 'GY', name: 'Guyana', code: '592' },
  { iso: 'HT', name: 'Haití', code: '509' },
  { iso: 'HN', name: 'Honduras', code: '504' },
  { iso: 'HK', name: 'Hong Kong', code: '852' },
  { iso: 'HU', name: 'Hungría', code: '36' },
  { iso: 'IN', name: 'India', code: '91' },
  { iso: 'ID', name: 'Indonesia', code: '62' },
  { iso: 'IQ', name: 'Irak', code: '964' },
  { iso: 'IR', name: 'Irán', code: '98' },
  { iso: 'IE', name: 'Irlanda', code: '353' },
  { iso: 'IM', name: 'Isla de Man', code: '44' },
  { iso: 'IS', name: 'Islandia', code: '354' },
  { iso: 'KY', name: 'Islas Caimán', code: '1' },
  { iso: 'CK', name: 'Islas Cook', code: '682' },
  { iso: 'FO', name: 'Islas Feroe', code: '298' },
  { iso: 'FK', name: 'Islas Malvinas', code: '500' },
  { iso: 'MP', name: 'Islas Marianas del Norte', code: '1' },
  { iso: 'MH', name: 'Islas Marshall', code: '692' },
  { iso: 'SB', name: 'Islas Salomón', code: '677' },
  { iso: 'TC', name: 'Islas Turcas y Caicos', code: '1' },
  { iso: 'VG', name: 'Islas Vírgenes Británicas', code: '1' },
  { iso: 'VI', name: 'Islas Vírgenes de EE. UU.', code: '1' },
  { iso: 'IL', name: 'Israel', code: '972' },
  { iso: 'IT', name: 'Italia', code: '39' },
  { iso: 'JM', name: 'Jamaica', code: '1' },
  { iso: 'JP', name: 'Japón', code: '81' },
  { iso: 'JE', name: 'Jersey', code: '44' },
  { iso: 'JO', name: 'Jordania', code: '962' },
  { iso: 'KZ', name: 'Kazajistán', code: '7' },
  { iso: 'KE', name: 'Kenia', code: '254' },
  { iso: 'KG', name: 'Kirguistán', code: '996' },
  { iso: 'KI', name: 'Kiribati', code: '686' },
  { iso: 'KW', name: 'Kuwait', code: '965' },
  { iso: 'LA', name: 'Laos', code: '856' },
  { iso: 'LS', name: 'Lesoto', code: '266' },
  { iso: 'LV', name: 'Letonia', code: '371' },
  { iso: 'LB', name: 'Líbano', code: '961' },
  { iso: 'LR', name: 'Liberia', code: '231' },
  { iso: 'LY', name: 'Libia', code: '218' },
  { iso: 'LI', name: 'Liechtenstein', code: '423' },
  { iso: 'LT', name: 'Lituania', code: '370' },
  { iso: 'LU', name: 'Luxemburgo', code: '352' },
  { iso: 'MO', name: 'Macao', code: '853' },
  { iso: 'MK', name: 'Macedonia del Norte', code: '389' },
  { iso: 'MG', name: 'Madagascar', code: '261' },
  { iso: 'MY', name: 'Malasia', code: '60' },
  { iso: 'MW', name: 'Malaui', code: '265' },
  { iso: 'MV', name: 'Maldivas', code: '960' },
  { iso: 'ML', name: 'Malí', code: '223' },
  { iso: 'MT', name: 'Malta', code: '356' },
  { iso: 'MA', name: 'Marruecos', code: '212' },
  { iso: 'MQ', name: 'Martinica', code: '596' },
  { iso: 'MU', name: 'Mauricio', code: '230' },
  { iso: 'MR', name: 'Mauritania', code: '222' },
  { iso: 'YT', name: 'Mayotte', code: '262' },
  { iso: 'MX', name: 'México', code: '52' },
  { iso: 'FM', name: 'Micronesia', code: '691' },
  { iso: 'MD', name: 'Moldavia', code: '373' },
  { iso: 'MC', name: 'Mónaco', code: '377' },
  { iso: 'MN', name: 'Mongolia', code: '976' },
  { iso: 'ME', name: 'Montenegro', code: '382' },
  { iso: 'MS', name: 'Montserrat', code: '1' },
  { iso: 'MZ', name: 'Mozambique', code: '258' },
  { iso: 'MM', name: 'Myanmar', code: '95' },
  { iso: 'NA', name: 'Namibia', code: '264' },
  { iso: 'NR', name: 'Nauru', code: '674' },
  { iso: 'NP', name: 'Nepal', code: '977' },
  { iso: 'NI', name: 'Nicaragua', code: '505' },
  { iso: 'NE', name: 'Níger', code: '227' },
  { iso: 'NG', name: 'Nigeria', code: '234' },
  { iso: 'NU', name: 'Niue', code: '683' },
  { iso: 'NO', name: 'Noruega', code: '47' },
  { iso: 'NC', name: 'Nueva Caledonia', code: '687' },
  { iso: 'NZ', name: 'Nueva Zelanda', code: '64' },
  { iso: 'OM', name: 'Omán', code: '968' },
  { iso: 'NL', name: 'Países Bajos', code: '31' },
  { iso: 'PK', name: 'Pakistán', code: '92' },
  { iso: 'PW', name: 'Palaos', code: '680' },
  { iso: 'PS', name: 'Palestina', code: '970' },
  { iso: 'PA', name: 'Panamá', code: '507' },
  { iso: 'PG', name: 'Papúa Nueva Guinea', code: '675' },
  { iso: 'PY', name: 'Paraguay', code: '595' },
  { iso: 'PE', name: 'Perú', code: '51' },
  { iso: 'PF', name: 'Polinesia Francesa', code: '689' },
  { iso: 'PL', name: 'Polonia', code: '48' },
  { iso: 'PT', name: 'Portugal', code: '351' },
  { iso: 'PR', name: 'Puerto Rico', code: '1' },
  { iso: 'GB', name: 'Reino Unido', code: '44' },
  { iso: 'CF', name: 'República Centroafricana', code: '236' },
  { iso: 'CZ', name: 'República Checa', code: '420' },
  { iso: 'CG', name: 'República del Congo', code: '242' },
  { iso: 'CD', name: 'República Democrática del Congo', code: '243' },
  { iso: 'DO', name: 'República Dominicana', code: '1' },
  { iso: 'RE', name: 'Reunión', code: '262' },
  { iso: 'RW', name: 'Ruanda', code: '250' },
  { iso: 'RO', name: 'Rumania', code: '40' },
  { iso: 'RU', name: 'Rusia', code: '7' },
  { iso: 'WS', name: 'Samoa', code: '685' },
  { iso: 'AS', name: 'Samoa Americana', code: '1' },
  { iso: 'BL', name: 'San Bartolomé', code: '590' },
  { iso: 'KN', name: 'San Cristóbal y Nieves', code: '1' },
  { iso: 'SM', name: 'San Marino', code: '378' },
  { iso: 'MF', name: 'San Martín', code: '590' },
  { iso: 'PM', name: 'San Pedro y Miquelón', code: '508' },
  { iso: 'VC', name: 'San Vicente y las Granadinas', code: '1' },
  { iso: 'SH', name: 'Santa Elena', code: '290' },
  { iso: 'LC', name: 'Santa Lucía', code: '1' },
  { iso: 'ST', name: 'Santo Tomé y Príncipe', code: '239' },
  { iso: 'SN', name: 'Senegal', code: '221' },
  { iso: 'RS', name: 'Serbia', code: '381' },
  { iso: 'SC', name: 'Seychelles', code: '248' },
  { iso: 'SL', name: 'Sierra Leona', code: '232' },
  { iso: 'SG', name: 'Singapur', code: '65' },
  { iso: 'SX', name: 'Sint Maarten', code: '1' },
  { iso: 'SY', name: 'Siria', code: '963' },
  { iso: 'SO', name: 'Somalia', code: '252' },
  { iso: 'LK', name: 'Sri Lanka', code: '94' },
  { iso: 'ZA', name: 'Sudáfrica', code: '27' },
  { iso: 'SD', name: 'Sudán', code: '249' },
  { iso: 'SS', name: 'Sudán del Sur', code: '211' },
  { iso: 'SE', name: 'Suecia', code: '46' },
  { iso: 'CH', name: 'Suiza', code: '41' },
  { iso: 'SR', name: 'Surinam', code: '597' },
  { iso: 'TH', name: 'Tailandia', code: '66' },
  { iso: 'TW', name: 'Taiwán', code: '886' },
  { iso: 'TZ', name: 'Tanzania', code: '255' },
  { iso: 'TJ', name: 'Tayikistán', code: '992' },
  { iso: 'TL', name: 'Timor Oriental', code: '670' },
  { iso: 'TG', name: 'Togo', code: '228' },
  { iso: 'TK', name: 'Tokelau', code: '690' },
  { iso: 'TO', name: 'Tonga', code: '676' },
  { iso: 'TT', name: 'Trinidad y Tobago', code: '1' },
  { iso: 'TN', name: 'Túnez', code: '216' },
  { iso: 'TM', name: 'Turkmenistán', code: '993' },
  { iso: 'TR', name: 'Turquía', code: '90' },
  { iso: 'TV', name: 'Tuvalu', code: '688' },
  { iso: 'UA', name: 'Ucrania', code: '380' },
  { iso: 'UG', name: 'Uganda', code: '256' },
  { iso: 'UY', name: 'Uruguay', code: '598' },
  { iso: 'UZ', name: 'Uzbekistán', code: '998' },
  { iso: 'VU', name: 'Vanuatu', code: '678' },
  { iso: 'VE', name: 'Venezuela', code: '58' },
  { iso: 'VN', name: 'Vietnam', code: '84' },
  { iso: 'WF', name: 'Wallis y Futuna', code: '681' },
  { iso: 'YE', name: 'Yemen', code: '967' },
  { iso: 'DJ', name: 'Yibuti', code: '253' },
  { iso: 'ZM', name: 'Zambia', code: '260' },
  { iso: 'ZW', name: 'Zimbabue', code: '263' },
];

export const findCountry = (iso: string): Country | undefined =>
  COUNTRIES.find((c) => c.iso === iso);

/**
 * Para códigos compartidos ('1', '7', '44'…) el primero de esta lista gana
 * al parsear un E.164. Los frecuentes van primero (US gana a Canadá en '1').
 */
const PARSE_PRIORITY: string[] = [...FREQUENT_ISOS, 'GB', 'RU', 'FI', 'CW', 'RE'];

const priorityRank = (iso: string): number => {
  const i = PARSE_PRIORITY.indexOf(iso);
  return i === -1 ? PARSE_PRIORITY.length : i;
};

/** Candidatos ordenados: código más largo gana; en empate, el prioritario. */
const PARSE_ORDER: Country[] = [...COUNTRIES].sort(
  (a, b) => b.code.length - a.code.length || priorityRank(a.iso) - priorityRank(b.iso),
);

/** Descompone un E.164 en país + dígitos nacionales. Fallback: Perú. */
export function parseE164(e164: string | undefined): { iso: string; digits: string } {
  if (!e164?.startsWith('+')) return { iso: 'PE', digits: '' };
  const raw = e164.slice(1);
  const match = PARSE_ORDER.find((c) => raw.startsWith(c.code));
  if (!match) return { iso: 'PE', digits: '' };
  return { iso: match.iso, digits: raw.slice(match.code.length) };
}

/** "Perú" → "peru": para que la búsqueda ignore tildes. */
export const normalize = (s: string): string =>
  s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase();
